# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
